name: SAST TEST

on:
  workflow_dispatch:

  push:
    branches:
    - main

  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/kang.yml


jobs:
  build-lin:
    uses: ./.github/workflows/kang.yml

