name: Call a reusable workflow and use its outputs

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        
  workflow_dispatch:

jobs:
  call-workflow:
    uses: kangkaihui/xFasterTransformer/.github/workflows/semgrep.yml@main

