name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    uses: kangkaihui/xFasterTransformer/.github/workflows/semgrep.yml@main
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
