name: Call a reusable workflow and use its outputs

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true
  workflow_dispatch: {}
  push:
    branches: ["main"]
jobs:
  call-workflow:
    uses: kangkaihui/xFasterTransformer/.github/workflows/semgrep.yml@main
    with:
     prod-branch: 'main'
     prod-scan: 'true'
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
